version: "3.9"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs

  redis:
    image: redis:latest
    command: redis-server --requirepass root
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: root
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - redis-network

volumes:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge